name: MultiplayerCore
version: 0.0.7
api-version: 1.19
author: dedose
main: me.abdullah.core.Core

commands:
  bank:
    description: A parent command to manage the user's bank
  accept:
    description: Executes the given pending action
  worldvalue:
    description: Changes the given world value